org: "drycc"
pull_policy: "Always"
docker_tag: "canary"
docker_registry: ""
platform_domain: ""
dhparam: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"
# requests_cpu: "100m"
# requests_memory: "50Mi"

# Any custom router annotations(https://github.com/drycc/router#annotations)
# which need to be applied can be specified as key-value pairs under "deployment_annotations"
#deployment_annotations:
  #<example-key>: <example-value>

# Any custom annotations for k8s services like http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws
# which need to be applied can be specified as key-value pairs under "service_annotations"
#service_annotations:
  #<example-key>: <example-value>

service:
  # Service type default to LoadBalancer
  type: LoadBalancer

  # If service.type is not set to NodePort, the following statement will be ignored.
  nodePort:
    builder: ""
    http: ""
    https: ""
    healthz: ""

global:
  use_rbac: false
  # Experimental feature to use Kubernetes ingress instead of Workflow's drycc-router.
  # If ingress_class is empty, use drycc-router
  # Otherwise, please check `kubernetes.io/ingress.class`
  # The cert-manager component must be installed
  ingress_class: ""
