apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    router.drycc.cc/routable: "true"
    app: apache
  annotations:
    # Demonstrates a subdomain of the router's default domain as well as a fully-qualified domain name
    router.drycc.cc/domains: apache,httpd.example.com
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
