{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: RoleBinding
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-router
subjects:
- kind: ServiceAccount
  name: drycc-router
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
